### PR TITLE
amethyst: warn if installing aur packages

### PR DESCRIPTION
**Pull request by fries1234**
This implements #62 

This is how it looks right now

image

### CODE REVIEW

**Review by orowith2os — APPROVED** [review]
LGTM

**Comment by mrshmllow** [comment]
too much to say it twice

**Comment by fries1234** [comment]
wdym by it saying it twice? if you mean the screenshot. i was just showing it with noconfirm on and off.

**Comment by not-my-segfault** [comment]
This should be toggle-able in the config (but true by default) and should display using `warn!()` IMO

**Comment by fries1234** [comment]
yeah you can toggle this with a config key

**Comment by fries1234** [comment]
the `aur_verification_prompt` key

**Comment by not-my-segfault** [comment]
> yeah you can toggle this with a config key

Oh, awesome! So long as it's a `warn!()` then, I see no issues with merging this. It's a good advisory

**Comment by Trivernis** [comment]
How about adding a "this warning can be disabled in the configuration file"?

**Comment by not-my-segfault** [comment]
> How about adding a "this warning can be disabled in the configuration file"?

This too, since this is a branch of Amethyst not an external fork, I can actually implement this right now

**Comment by mrshmllow** [comment]
i think it should be shorter

**Comment by mrshmllow** [comment]
maybe a part of the "review?" part

**Comment by not-my-segfault** [comment]
> i think it should be shorter

I feel like this is one of the situations where we should be big long and bold so that the user feels like they *should* read it, if it's a shorted warning at the review stage, I feel like a user would attempt to dismiss it without 2nd thought

**Comment by not-my-segfault** [comment]
image

How does this look?

**Comment by Trivernis** [comment]
"need to do" -> "claim to do" maybe?

**Comment by not-my-segfault** [comment]
Generally reworded it a bit
image

I'll also test to make sure the config keys apply

**Comment by not-my-segfault** [comment]
Config keys apply, looks good!

**Comment by mrshmllow** [comment]
a "don't show again" option would be cool

**Comment by not-my-segfault** [comment]
> a "don't show again" option would be cool

This is currently handled in the config, the user can simply adjust `~/.config/ame/config.toml` and set `aur_verification_prompt = false`

What do you think about a prompt that potentially would automatically change the key @Trivernis ?

**Comment by mrshmllow** [comment]
[y/a/n/]

**Comment by Trivernis** [comment]
> What do you think about a prompt that potentially would automatically change the key @Trivernis ?

@not-my-segfault the prompt itself isn't the problem. We can use a multi select or smth. 
Writing back the config key is a bit more advanced. We currently don't have a write-back implementation afaik and rewriting the config file means adding all the config values, even the default ones

**Comment by not-my-segfault** [comment]
> > What do you think about a prompt that potentially would automatically change the key @Trivernis ?
> 
> @not-my-segfault the prompt itself isn't the problem. We can use a multi select or smth. 
> Writing back the config key is a bit more advanced. We currently don't have a write-back implementation afaik and rewriting the config file means adding all the config values, even the default ones

I'd say that for now we can just go with what I have pushed then

**Review by Trivernis — APPROVED** [review]

**Comment by fries1234** [comment]
thank you everyone for the feedback 💖

**Pull request merged**
