### PR TITLE
Add Italian translation

### PR DESCRIPTION
**Pull request by musiclover382**

### CODE REVIEW

**Comment by not-my-segfault** [comment]
This looks good to me

**Comment by not-my-segfault** [comment]
Asked for review just to confirm localisation is set right

**Comment by Trivernis** [comment]
@fries1234 you're the expert here. Does the format look correct?

**Comment by fries1234** [comment]
looking at it, the format seems right. im just gonna compile it to see if it works and ill say if it works for me or not.

**Review by fries1234 — APPROVED** [review]
yeah this looks good :+1:

**Pull request merged**
