### PR TITLE
Parse config with config crate

### PR DESCRIPTION
**Pull request by fries1234**
This PR changes the parsing of the config to be done with the config crate.

### CODE REVIEW

**Comment by not-my-segfault** [comment]
This looks good so far, we've recently added a new config key for a custom sudo binary (See PR #26)

Just make sure to still have support for that, and then I see no reason not to merge

**Review by not-my-segfault — CHANGES_REQUESTED** [review]
This looks good so far, we've recently added a new config key for a custom sudo binary (See PR https://github.com/crystal-linux/amethyst/pull/26)

Just make sure to still have support for that, and then I see no reason not to merge

**Comment by fries1234** [comment]
ok i added sudo support

**Comment by mrshmllow** [comment]
no why have you moved the key randomly. it's `bin.sudo`

**Review by not-my-segfault — APPROVED** [review]

**Review by mrshmllow — COMMENTED** [review]
Noooooo

**Comment by fries1234** [comment]
> Noooooo

whats wrong?

**Comment by mrshmllow** [comment]
merge commits

**Comment by fries1234** [comment]
> merge commits

yeah michal said it was a github thing. xe said that "github calls anything a merge commit" even if its just a simple rebase

**Comment by not-my-segfault** [comment]
Yeah, this was a result of rebasing this branch against base, which isn't reflected in the commit history once merged. Just a GitHub thing

**Pull request merged**
