### PR TITLE
internal/detect: remove duplicate sudo prompt

### PR DESCRIPTION
**Pull request by fries1234**
removes a duplicate sudo prompt

fixes a bug with alternate sudo-likes, like `doas` which don't have a `-v` flag.

### CODE REVIEW

**Comment by fries1234** [comment]
@mrshmllow can you test this?

**Review by Trivernis — CHANGES_REQUESTED** [review]
This prompt is actually required because after starting the progress spinner, any sudo prompt will just get overwritten by that spinner

**Comment by fries1234** [comment]
well should the prompt be using the sudo builder?

**Comment by Trivernis** [comment]
In this case using the encapsulated way of calling sudo (with the prompt function) is probably cleaner

**Pull request closed without merging**
