### PR TITLE
Add a new logo

### PR DESCRIPTION
**Pull request by henrybarreto**
I thought I would give the project an own logo, so that is my try to do that.

There is no problem if it has got to be rejected.  😄 

Signed-off-by: Henry Barreto <me@henrybarreto.dev>

### CODE REVIEW

**Comment by SomethingGeneric** [comment]
Hey! This logo looks awesome. I assume you created it yourself? (Just want to clarify so we don't get in any licensing hot-water.)
Thanks for taking the time to improve the readme!

**Comment by henrybarreto** [comment]
> Hey! This logo looks awesome. I assume you created it yourself? (Just want to clarify so we don't get in any licensing hot-water.) Thanks for taking the time to improve the readme!

Yeah! I made it on Figma from zero.

**Comment by not-my-segfault** [comment]
This looks fantastic! If possible could you potentially give the logo more contrast, and make it a `logo.svg` file in the repo that gets referenced by the README.md file?

**Comment by SomethingGeneric** [comment]
> Yeah! I made it on Figma from zero.
Awesome!



> This looks fantastic! If possible could you potentially give the logo more contrast, and make it a `logo.svg` file in the repo that gets referenced by the README.md file?

Yeah, my next suggestion was this, too. 

Otherwise I think this is all set! Thanks again!

**Comment by henrybarreto** [comment]
> This looks fantastic! If possible could you potentially give the logo more contrast, and make it a `logo.svg` file in the repo that gets referenced by the README.md file?

Of course, I can.

I'll fix it now.

**Comment by henrybarreto** [comment]
done!

**Comment by SomethingGeneric** [comment]
Hey @henrybarreto you changed the README but forgot to add the `logo.svg` file to the repo haha

**Comment by henrybarreto** [comment]
@SomethingGeneric, sorry. lol

I believe it right now.

**Review by SomethingGeneric — APPROVED** [review]
Awesome! looks good to me!

**Comment by SomethingGeneric** [comment]
@not-my-segfault i'm gonna leave the final merge for you in case there's something i don't know about

**Comment by not-my-segfault** [comment]
LGTM, going to merge this

**Pull request merged**
